apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-doctor

commonLabels:
  app.kubernetes.io/part-of: node-doctor

resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: supporttools/node-doctor-controller
    newTag: latest
